quotes = [
    "Todo:", "Tasks:", "Doing well.", "Keep it up!", "You can do it.",
    "Good stuff.", "Make it happen!", ":D", "Nicely done.",
    "Things to do...", "Plan it. Do it. Succeed.", "Forward momentum.",
    "Making progress.", "I am a todo window?! How did I get in this strange place?",
    "Slow and steady.",
    "The secret of joy in work is contained in one word - excellence. To know how to do something well is to enjoy it.",
    "Knowing trees, I understand the meaning of patience. Knowing grass, I can appreciate persistence.",
    "Success consists of going from failure to failure without loss of enthusiasm.",
    "Successful and unsuccessful people do not vary greatly in their abilities. They vary in their desires to reach their potential.",
    "If you can imagine it, you can achieve it; if you can dream it, you can become it.",
    "Change your thoughts and you change your world.",
    "Out of clutter, find Simplicity. From discord, find Harmony. In the middle of difficulty lies Opportunity.",
    "You miss 100%% of the shots you don't take.",
    "If you don't pay appropriate attention to what has your attention, it will take more of your attention than it deserves.",
    "The miracle is not that we do this work, but that we are happy to do it.",
    "Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.",
    "Big jobs usually go to the men who prove their ability to outgrow small ones.",
    "Never give up, for that is just the place and time that the tide will turn.",
    "You will never win if you never begin.",
    "Let's roll.",
    "I think, therefore, I am.",
    "What's done is done.",
    "Attack in all directions!",
    "No day but today.",
    "Attitude is everything.",
    "Whatever happens, take responsibility.",
    "Know thyself.",
    "Do it now!",
    "The buck stops here.",
    "Never, never, never give up.",
    "The most important thing is not to stop questioning.",
    "Only those who dare to fail greatly can ever achieve greatly.",
    "Thinking will not overcome fear but action will.",
    "Facts do not cease to exist because they are ignored.",
    "A creative person is motivated by the desire to achieve, not by the desire to beat others.",
    "If you aren't fired with enthusiasm, you will be fired with enthusiasm.",
    "Would you be shocked if I put on something more comfortable?",
    "Frankly, my dear, I don't give a damn!",
    "We don't see things as they are, we see things as we are.",
    "If you don't know where you are going you will probably end up somewhere else.",
    "I am a great believer in luck, and I find the harder I work, the more I have of it.",
    "The greatest revenge is to accomplish what others say you cannot do.",
    "All glory comes from daring to begin.",
    "If you change nothing, nothing changes.",
    "You might as well remember that nothing can bring you success but yourself.",
    "A goal is a dream with a deadline.",
    "Nothing is particularly hard if you divide it into small jobs.",
    "Once you have a clear picture of your priorities - organize around them.",
    "High achievement always takes place in the framework of high expectation.",
    "This one step, choosing a goal and sticking to it, changes everything.",
    "A good plan today is better than a great plan tomorrow.",
    "Knowing what to do is very, very different than actually doing it.",
    "First, say to yourself what you would be; and then do what you have to do.",
    "A mistake is only a mistake if you don't learn from it.",
    "It is amazing what you can accomplish if you do not care who gets the credit.",
    "A person who graduated yesterday and stops studying today is uneducated tomorrow.",
    "Don't let yesterday take up too much of today.",
    "Strive for excellence, not perfection.",
    "Failing to plan is planning to fail.",
    "Plan you work and work your plan.",
    "The discipline of writing something down is the first step toward making it happen.",
    "The best way to predict the future is to create it.",
    "I'll always cherish the original misconception I had of you.",
    "It is not necesssary to understand things in order to argue about them.",
    "In the middle of every difficulty lies opportunity",
    "If you change nothing, nothing changes",
    "You miss every shot you don't take.",
    "Stop thinking of what could go wrong and start thinking of what could go right",
    "If you waste time, time will waste you!",
    "Yes I Can!",
    "Do it Now!",
    "No day but today"
]
